Add ability to check for core include files

diff --git a/rd-installer b/rd-installer
--- a/rd-installer
+++ b/rd-installer
@@ -9,6 +9,9 @@
 
 # Ensure variables, functions and prompts exist
 if [[ ! -e "includes/variables.sh" ]] || [[ ! -e "includes/functions.sh" ]] || [[ ! -e "includes/prompts.sh" ]]; then
+	echo "We can not start the installer because some files are missing, try re-downloading the installer!"
+	exit 1
+else
 	source includes/variables.sh
 	source includes/functions.sh
 	source includes/prompts.sh
